### ISSUE TITLE
Fix mm cli opkg

### ISSUE THREAD

**Issue by JamesVorder** [MassMesh/mm-toolbox#7]
The python dependencies aren't being installed correctly...

Maybe try https://anthony-tuininga.github.io/cx_Freeze/

**Comment by JamesVorder** [comment]
@wfleurant @cure Should we consider this issue closed now that the tool can be invoked with python?

**Comment by wfleurant** [comment]
what the heck was that, in `__init__.py` right? 
![image](https://user-images.githubusercontent.com/5460439/84228253-8aef5f80-aab4-11ea-8539-daa5cdbb3bf0.png)

**Comment by wfleurant** [comment]
MIB now has a has a `mm` busybox

https://github.com/MassMesh/meta-imagebuilder/pull/55/commits/7938c7d4f44fd5ea919711cc7e64191351a4f58e
